  CREATE TABLE somatic_mutations (
  	 HugoSymbol VARCHAR (20) NOT NULL, 
	 EntrezGeneId INT NOT NULL, 
	 Center  BLOB  NOT NULL, 
	 NCBIBuild VARCHAR (20) NOT NULL, 
	 Chromosome VARCHAR (20) NOT NULL, 
	 Startposition INT  NOT NULL, 
	 Endposition INT NOT NULL, 
	 Strand VARCHAR (5) NOT NULL, 
	 VariantClassification VARCHAR (50) NOT NULL, 
	 VariantType VARCHAR (20) NOT NULL, 
	 ReferenceAllele BLOB NOT NULL, 
	 TumorSeqAllele1 BLOB NOT NULL, 
	 TumorSeqAllele2 BLOB NOT NULL, 
	 dbSNPRS VARCHAR (20), 
	 dbSNPValStatus BLOB, 
	 TumorSampleBarcode VARCHAR (50) NOT NULL, 
	 MatchedNormSampleBarcode VARCHAR (50) NOT NULL, 
	 MatchNormSeqAllele1 BLOB, 
	 MatchNormSeqAllele2 BLOB, 
	 TumorValidationAllele1 BLOB, 
	 TumorValidationAllele2 BLOB, 
	 MatchNormValidationAllele1 BLOB, 
	 MatchNormValidationAllele2 BLOB, 
	 VerificationStatus VARCHAR (20), 
	 ValidationStatus VARCHAR (20) NOT NULL, 
	 MutationStatus VARCHAR (50) NOT NULL, 
	 SequencingPhase VARCHAR (20), 
	 SequenceSource VARCHAR (50) NOT NULL, 
	 ValidationMethod BLOB NOT NULL, 
	 Score VARCHAR (20) , 
	 BAMFile VARCHAR (20), 
	 Sequencer BLOB NOT NULL, 
	 TumorSampleUUID VARCHAR (100) NOT NULL, 
	 MatchedNormSampleUUID VARCHAR (100) NOT NULL, 
	 COSMICCodon VARCHAR (100), 
	 COSMICGene VARCHAR (20), 
	 TranscriptID VARCHAR (20), 
	 Exon VARCHAR (20), 
	 ChromChange VARCHAR (50), 
	 AAChange VARCHAR (20), 
	 GenomePlusMinus10Bp BLOB, 
	 DrugTarget VARCHAR (20), 
	 TTotCov VARCHAR (20), 
	 TVarCov VARCHAR (20), 
	 NTotCov VARCHAR (20), 
	 NVarCov VARCHAR (20), 
	 dbSNPPopFreq BLOB 
) ENGINE=MyISAM;
